### PR TITLE
TEST-9: Assign reviewer ignore bot

### PR DESCRIPTION
**Pull request by romshark**
resolves:
TEST-9
TEST-10

affects:
TEST-3

notes:

### CODE REVIEW

**Comment by romshark** [comment]
comment 1

**Comment by romshark** [comment]
comment 2

**Review by romgithubtest — APPROVED** [review]
approved on [JIRA](https://romsharktestjira.atlassian.net//browse/TEST-12)

**Review by romgithubtest — APPROVED** [review]
approved on [JIRA](https://romsharktestjira.atlassian.net//browse/TEST-13)

**Pull request closed without merging**
